import * as yup from "yup";

export const formConfig = [
  {
    Header: "Id",
    accessor: "Id",
    type: "text",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "Enabled",
    accessor: "Enabled",
    type: "bool",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "ClientId",
    accessor: "ClientId",
    type: "text",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "ProtocolType",
    accessor: "ProtocolType",
    type: "text",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "RequireClientSecret",
    accessor: "RequireClientSecret",
    type: "bool",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "ClientName",
    accessor: "ClientName",
    type: "text",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "Description",
    accessor: "Description",
    type: "text",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "ClientUri",
    accessor: "ClientUri",
    type: "text",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "LogoUri",
    accessor: "LogoUri",
    type: "text",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "RequireConsent",
    accessor: "RequireConsent",
    type: "bool",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "AllowRememberConsent",
    accessor: "AllowRememberConsent",
    type: "bool",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "AlwaysIncludeUserClaimsInIdToken",
    accessor: "AlwaysIncludeUserClaimsInIdToken",
    type: "bool",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "RequirePkce",
    accessor: "RequirePkce",
    type: "bool",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "AllowPlainTextPkce",
    accessor: "AllowPlainTextPkce",
    type: "bool",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "RequireRequestObject",
    accessor: "RequireRequestObject",
    type: "bool",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "AllowAccessTokensViaBrowser",
    accessor: "AllowAccessTokensViaBrowser",
    type: "bool",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "FrontChannelLogoutUri",
    accessor: "FrontChannelLogoutUri",
    type: "text",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "FrontChannelLogoutSessionRequired",
    accessor: "FrontChannelLogoutSessionRequired",
    type: "bool",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "BackChannelLogoutUri",
    accessor: "BackChannelLogoutUri",
    type: "text",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "BackChannelLogoutSessionRequired",
    accessor: "BackChannelLogoutSessionRequired",
    type: "bool",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "AllowOfflineAccess",
    accessor: "AllowOfflineAccess",
    type: "bool",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "IdentityTokenLifetime",
    accessor: "IdentityTokenLifetime",
    type: "text",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "AllowedIdentityTokenSigningAlgorithms",
    accessor: "AllowedIdentityTokenSigningAlgorithms",
    type: "text",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "AccessTokenLifetime",
    accessor: "AccessTokenLifetime",
    type: "text",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "AuthorizationCodeLifetime",
    accessor: "AuthorizationCodeLifetime",
    type: "text",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "ConsentLifetime",
    accessor: "ConsentLifetime",
    type: "text",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "AbsoluteRefreshTokenLifetime",
    accessor: "AbsoluteRefreshTokenLifetime",
    type: "text",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "SlidingRefreshTokenLifetime",
    accessor: "SlidingRefreshTokenLifetime",
    type: "text",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "RefreshTokenUsage",
    accessor: "RefreshTokenUsage",
    type: "text",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "UpdateAccessTokenClaimsOnRefresh",
    accessor: "UpdateAccessTokenClaimsOnRefresh",
    type: "bool",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "RefreshTokenExpiration",
    accessor: "RefreshTokenExpiration",
    type: "text",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "AccessTokenType",
    accessor: "AccessTokenType",
    type: "text",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "EnableLocalLogin",
    accessor: "EnableLocalLogin",
    type: "bool",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "IncludeJwtId",
    accessor: "IncludeJwtId",
    type: "bool",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "AlwaysSendClientClaims",
    accessor: "AlwaysSendClientClaims",
    type: "bool",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "ClientClaimsPrefix",
    accessor: "ClientClaimsPrefix",
    type: "text",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "PairWiseSubjectSalt",
    accessor: "PairWiseSubjectSalt",
    type: "text",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "Created",
    accessor: "Created",
    type: "text",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "Updated",
    accessor: "Updated",
    type: "text",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "LastAccessed",
    accessor: "LastAccessed",
    type: "text",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "UserSsoLifetime",
    accessor: "UserSsoLifetime",
    type: "text",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "UserCodeType",
    accessor: "UserCodeType",
    type: "text",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "DeviceCodeLifetime",
    accessor: "DeviceCodeLifetime",
    type: "text",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
  {
    Header: "NonEditable",
    accessor: "NonEditable",
    type: "bool",
    table: "Clients",
    colSize: 6,
    hidden: false,
    initialValue: "",
  },
];

export const yupSchema = yup.object({
  Id: yup.number().required("Id is required."),
  Enabled: yup.bool().required("Enabled is required."),
  ClientId: yup.string().required("ClientId is required."),
  ProtocolType: yup.string().required("ProtocolType is required."),
  RequireClientSecret: yup.bool().required("RequireClientSecret is required."),
  ClientName: yup.string().nullable(),
  Description: yup.string().nullable(),
  ClientUri: yup.string().nullable(),
  LogoUri: yup.string().nullable(),
  RequireConsent: yup.bool().required("RequireConsent is required."),
  AllowRememberConsent: yup
    .bool()
    .required("AllowRememberConsent is required."),
  AlwaysIncludeUserClaimsInIdToken: yup
    .bool()
    .required("AlwaysIncludeUserClaimsInIdToken is required."),
  RequirePkce: yup.bool().required("RequirePkce is required."),
  AllowPlainTextPkce: yup.bool().required("AllowPlainTextPkce is required."),
  RequireRequestObject: yup
    .bool()
    .required("RequireRequestObject is required."),
  AllowAccessTokensViaBrowser: yup
    .bool()
    .required("AllowAccessTokensViaBrowser is required."),
  FrontChannelLogoutUri: yup.string().nullable(),
  FrontChannelLogoutSessionRequired: yup
    .bool()
    .required("FrontChannelLogoutSessionRequired is required."),
  BackChannelLogoutUri: yup.string().nullable(),
  BackChannelLogoutSessionRequired: yup
    .bool()
    .required("BackChannelLogoutSessionRequired is required."),
  AllowOfflineAccess: yup.bool().required("AllowOfflineAccess is required."),
  IdentityTokenLifetime: yup
    .number()
    .required("IdentityTokenLifetime is required."),
  AllowedIdentityTokenSigningAlgorithms: yup.string().nullable(),
  AccessTokenLifetime: yup
    .number()
    .required("AccessTokenLifetime is required."),
  AuthorizationCodeLifetime: yup
    .number()
    .required("AuthorizationCodeLifetime is required."),
  ConsentLifetime: yup.number().nullable(),
  AbsoluteRefreshTokenLifetime: yup
    .number()
    .required("AbsoluteRefreshTokenLifetime is required."),
  SlidingRefreshTokenLifetime: yup
    .number()
    .required("SlidingRefreshTokenLifetime is required."),
  RefreshTokenUsage: yup.number().required("RefreshTokenUsage is required."),
  UpdateAccessTokenClaimsOnRefresh: yup
    .bool()
    .required("UpdateAccessTokenClaimsOnRefresh is required."),
  RefreshTokenExpiration: yup
    .number()
    .required("RefreshTokenExpiration is required."),
  AccessTokenType: yup.number().required("AccessTokenType is required."),
  EnableLocalLogin: yup.bool().required("EnableLocalLogin is required."),
  IncludeJwtId: yup.bool().required("IncludeJwtId is required."),
  AlwaysSendClientClaims: yup
    .bool()
    .required("AlwaysSendClientClaims is required."),
  ClientClaimsPrefix: yup.string().nullable(),
  PairWiseSubjectSalt: yup.string().nullable(),
  Created: yup.string().required("Created is required."),
  Updated: yup.string().nullable(),
  LastAccessed: yup.string().nullable(),
  UserSsoLifetime: yup.number().nullable(),
  UserCodeType: yup.string().nullable(),
  DeviceCodeLifetime: yup.number().required("DeviceCodeLifetime is required."),
  NonEditable: yup.bool().required("NonEditable is required."),
});

export const initialValues = getInitialValues(formConfig);

function getInitialValues(formConfig) {
  let obj = {};
  formConfig.map((c) => {
    obj[c.name] = c.initialValue;
  });

  return obj;
}
